In [303]:
import numpy as np

In [304]:
a = np.array([1,2,3,4,5,6])

In [305]:
a[1]

2

In [306]:
a[0:2]

array([1, 2])

In [307]:
a[::2]

array([1, 3, 5])

In [308]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [309]:
b = a[3:]
b 

array([4, 5, 6])

In [310]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [311]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [312]:
a[1, 3]
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [313]:
a.ndim

2

In [314]:
a.shape

(3, 4)

In [315]:
a.size

12

In [316]:
a.dtype

dtype('int32')

In [317]:
np.zeros(2)

array([0., 0.])

In [318]:
np.empty(2)

array([0., 0.])

In [319]:
np.arange(4)

array([0, 1, 2, 3])

In [320]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [321]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [322]:
arr = np.array([2,3,4,1,5,7,6])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [323]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [324]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [325]:
a = np.arange(6)
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [326]:
np.reshape(a, (1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [327]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [328]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [329]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [330]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [331]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a > 5])

[ 6  7  8  9 10 11 12]


In [332]:
b = np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [333]:
a[b]

array([1, 2, 3, 4])

In [334]:
a1 = np.array([[1, 1],
           [2, 2]])
a2 = np.array([[3, 3],
           [4, 4]])
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [335]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [336]:
x = np.arange(1, 25).reshape(2, 12)
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [337]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [338]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [339]:
data - ones

array([0, 1])

In [340]:
data * data

array([1, 4])

In [341]:
data / data

array([1., 1.])

In [342]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [343]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [344]:
b.sum(axis=1)

array([2, 4])

In [345]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])